#!/usr/bin/expect -f
set timeout 60
set pass "Hjj123456"
set addr "/ip4/8.136.129.162/tcp/4001/p2p/12D3KooWLd56gZpYP2Q1hejJ2juN6GoYQcA9VMTcek6aetTRfwYi"
set server_vip "10.98.237.157"

# Prime sudo
spawn sudo -v
expect {
    -re "Password:" {
        send "$pass\r"
    }
}
expect eof

# Run node
spawn sudo ./dist/bin/p2p-node-darwin-arm64 -port 4002 -config ./config_mac1 -bootstrap $addr
expect {
    "meshlink is running" {
        send_user "\nNODE_READY\n"
    }
}

# Wait for DHT
sleep 20

# Ping
spawn ping -c 5 $server_vip
expect {
    "5 packets transmitted, 5 packets received" {
        send_user "\n_PING_SUCCESS_\n"
    }
    timeout {
        send_user "\n_PING_FAILED_\n"
    }
}

# Cleanup
spawn sudo pkill p2p-node
expect eof
