// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInfo() {
  return window['go']['main']['App']['GetInfo']();
}

export function GetPeerCount() {
  return window['go']['main']['App']['GetPeerCount']();
}

export function StartVPN(arg1) {
  return window['go']['main']['App']['StartVPN'](arg1);
}

export function StopVPN() {
  return window['go']['main']['App']['StopVPN']();
}
