// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInfo():Promise<Array<string>>;

export function GetPeerCount():Promise<number>;

export function StartVPN(arg1:string):Promise<string>;

export function StopVPN():Promise<void>;
